[agents.default]
llm = "openai"
openai_api_key = "XXXXX"

[agents.bob]
llm = "openai"
openai_api_key = "XXXXX"
vector_db_type = "Chroma"
vector_db_embedding = "openai"
vector_db_path = "./db/chroma"

[agents.tutor]
llm = "openai"
openai_api_key = "XXXXX"
vector_db_type = "Chroma"
vector_db_embedding = "openai"
vector_db_path = "./db/chroma"
